{% set name = "pys2index" %}
{% set version = "0.1.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/benbovy/pys2index/archive/{{ version }}.tar.gz
  sha256: 8904a0c17490deb022fb3650118ea3e27208998521024b6512b613566253ccc3
  patches:
    - 0001-fix-cmake.patch

build:
  number: 7
  script: {{ PYTHON }} -m pip install . --no-deps -vv --ignore-installed --no-cache-dir --no-build-isolation

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - scikit-build-core                      # [build_platform != target_platform]
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - cmake
    - make  # [unix]
  host:
    - python
    # In xtensor 0.26, all the header files were moved to new locations.
    # This corresponds to xtensor-python 0.28 and requires upstream changes.
    # As upstream is not being developed actively anymore, that is not likely
    # to happen, though the changes are fairly small, making a patch feasible.
    - xtensor-python >=0.26,<0.28a0
    - pybind11
    - pip
    - scikit-build-core
    - numpy
    - libabseil  # [not linux]
    - s2geometry
  run:
    - python

test:
  source_files:
    - tests
  requires:
    - pytest
  imports:
    - pys2index
  commands:
    - pytest

about:
  home: https://github.com/benbovy/pys2index
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Python/NumPy compatible geographical index based on s2geometry'

extra:
  recipe-maintainers:
    - benbovy
    - zklaus
